# -*- coding: utf-8 -*-
"""Summarization_zecide.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Su4Psl5pOV10ANrN9q7kSJ4fRDlRuUjm
"""

# ! pip install transformers

from transformers import pipeline

#append the articles here for summarization 

article=r"""Mondal has recently tendered his resignation from his current position as executive director & head of retail banking in Axis Bank. CSB Bank on Friday announced that its board has appointed Pralay Mondal as the bank’s President (Retail, SME, Operations and IT). Mondal is expected to join the Kerala-based lender in September 2020.
Mondal has recently tendered his resignation from his current position as executive director & head of retail banking in Axis Bank.CSB Bank, formerly known as Catholic Syrian Bank, was listed in December 2019 and on last Monday the bank reported a net profit of Rs 12.72 crores for FY 20, thereby breaking a streak of continuous losses.CSB had reported a net loss of Rs 197.42 crores in FY 19.
Mondal has around 30 years of banking experience across multiple business and functions including retail assets, retail liabilities, business banking, products and technology. Before joining Axis Bank, Mondal was the Senior Group President and Head of Retail and Business Banking at Yes Bank. Prior to that he had a 12 years’ stint at HDFC Bank and was earlier associated with Standard Chartered Bank, Wipro InfoTech and Colgate Palmolive.
Commenting on the development, MD & CEO C VR Rajendran said “We are delighted and excited with the appointment of Mondal as President (Retail, SME, Operations and IT) and look forward to his playing a key leadership role at the Bank. Mondal is a proven trailblazer who brings strong commercial banking expertise and experience to CSB Bank. He has an excellent track record of having built retail and SME businesses, while maintaining healthy portfolio quality and service levels. I am confident that we have selected the choicest person for CSB Bank and that he will drive strong and healthy business growth in the years ahead."""

from transformers import BartTokenizer, BartForConditionalGeneration, BartConfig
# see ``examples/summarization/bart/evaluate_cnn.py`` for a longer example
model = BartForConditionalGeneration.from_pretrained('facebook/bart-large-cnn')
tokenizer = BartTokenizer.from_pretrained('facebook/bart-large-cnn')
inputs = tokenizer.batch_encode_plus([article], max_length=1024, return_tensors='pt')
# Generate Summary
summary_ids = model.generate(inputs['input_ids'], num_beams=4, max_length=40, early_stopping=True)
print([tokenizer.decode(g, skip_special_tokens=True, clean_up_tokenization_spaces=False) for g in summary_ids])

